workflows:
  ios-workflow:
    name: Kharetat Elnagah iOS

    integrations:
      app_store_connect: itaaleem

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.elshroq.sheetvault

    scripts:
      - name: Build iOS app
        script: |
          cd src
          xcodebuild \
            -project *.xcodeproj \
            -scheme "KharetatElnagah" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath ../build/KharetatElnagah.xcarchive \
            archive

    artifacts:
      - build/KharetatElnagah.xcarchive/**

    publishing:
      app_store_connect:
        auth: integration

